package com.fosanzdev.T11.Ej5Adv.ItemCore;

public enum Modifier {
    HEALTH, SPEED, POWER, FIRE_RESISTANCE, WATER_BREATHING, INVISIBILITY,
    STRENGTH, JUMP_BOOST, REGENERATION, NIGHT_VISION, HASTE, ABSORPTION,
    SATURATION, LUCK, UNLUCK, POISON, WITHER, BLINDNESS, HUNGER, WEAKNESS,
    SLOWNESS, FATIGUE, MINING_FATIGUE, BAD_LUCK, BAD_OMEN, HERO_OF_THE_VILLAGE
}
