public class Ej19 {

    /**
     * Method used to validate if a NIF is valid or not
     * @param nifStr String with 8 numbers and 1 letter
     * @return a boolean response, saying if it's valid or not
     */
    public static boolean validarNIF(String nifStr){

        if (nifStr.length() != 9){
            System.out.println("Invalid input");
            return false;
        }

        //Creating a DNI substring with only the numbers
        String dniStr = nifStr.substring(0, nifStr.length()-1);

        //if the dni generated by "calcularNIF" method equals the given NIF, it's a valid input
        return Ej18.calcularNIF(dniStr).equals(nifStr);
    }
    public static void main(String[] args) {
        System.out.println(validarNIF("54375889W"));
    }
}
